# Generated by Django 3.0.4 on 2020-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now=True, verbose_name='Data  de registro')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Último login')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descricao')),
                ('eventYear', models.DateField(auto_now_add=True, verbose_name='Data do evento')),
            ],
            options={
                'verbose_name': 'Evento importante',
                'verbose_name_plural': 'Eventos importantes',
            },
        ),
    ]
